### ISSUE TITLE
Do not display icons in Android version 5.1.1

### ISSUE THREAD

**Issue by mmfarzaneh** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#16] opened 2021-02-04 11:52 UTC
Hi dear 
In Android 6 and above, it shows icons without any problem, but in Android 5, it does not show. Can you help me?
Thank you

**Comment by MahdiFarzami** [comment] 2021-04-10 10:26
i have same probleam.

**Comment by shwetachauhan-simform** [comment] 2021-04-28 15:09
@mmfarzaneh , @MahdiFarzami : I have checked in 5.1.1 emulator and it's working. Can you please share more detail??

**Comment by ShwetaChauhan18** [comment] 2021-09-05 13:39
not able to reproduce

**Closed by ShwetaChauhan18** 2021-09-05 13:39 UTC
